name: 'Check formatting of repository files'
on:
  - push

jobs:
  check-formatting-with-ruff:
    name: Check Python formatting with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v3
      - uses: astral-sh/ruff-action@v3

  check-formatting-with-snakefmt:
    name: Check Snakemake formatting with snakefmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - run: uv run snakefmt --check --compact-diff .

  check-formatting-with-markdownlint-cli2:
    name: Check Markdown formatting with pymarkdownlnt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - run: uv run pymarkdownlnt scan .
